<?php
function recent_news_menu() {
    $items = array();
    $items['display_recent_news/%/%'] = array(
            'access arguments' => array('access content'),
            'page callback' => 'recent_news',
            'page arguments' => array(1, 2),
            'type' => MENU_CALLBACK,
        );
    return $items;
}

function recent_news($js, $nid) {
    if ($js == 'nojs') {
        drupal_goto('node/' . $node->nid);
    }
    $node = node_load($nid);
    $build = node_view($node);
    $html = render($build);
    $commands = array();
    $commands[] = ajax_command_html('#news-ajax-wrapper', $html);
    print ajax_render($commands);
    exit;
}
