<?php
function matchDNA($sequence) {
    $letters = str_split($sequence);
    $matching_string = '';
    foreach($letters as $letter) {
        $match;
        switch($letter) {
            case 'C':
                $match = 'G';
                break;
            case 'G':
                $match = 'C';
                break;
            case 'T':
                $match = 'A';
                break;
            case 'A':
                $match = 'T';
                break;
        }
        $matching_string .= $match;
    }
    return $matching_string;
}
