<?php
function dna_menu() {
    $items = array();
    $items['dna_match'] = array(
            'title' => 'DNA Matcher',
            'access callback' => TRUE,
            'page callback' => 'drupal_get_form',
            'page arguments' => array('dna_form'),
            'type' => MENU_NORMAL_ITEM,
        );
    $items['dna_success_page'] = array(
            'title' => "DNA Matcher Success",
            'access callback' => TRUE,
            'page callback' => 'dna_success',
            'type' => MENU_CALLBACK,
        );
    return $items;
}

function dna_form() {
    $form = array();
    $form['sequence'] = array(
            '#title' => 'DNA Sequence',
            '#type' => 'textfield',
            '#description' => 'Enter one half of a DNA Helix and the other half will be returned.<br>Valid characters: A, C, G, T',
            '#element_validate' => array('sequence_input_validation'),
        );
    $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Submit',
        );
    return $form;
}

function sequence_input_validation($element) {
    $valid_letters = ['A', 'T', 'C', 'G'];
    $letters = str_split($element['#value']);
    foreach($letters as $letter) {
        if (!in_array($letter, $valid_letters)) {
            form_error($element, t("Your phrase includes unallowed characters."));
        }
    }
}

function dna_form_submit($form, &$form_state) {
    $original = $form_state['values']['sequence'];
    $results = matchDNA($original);
    $_SESSION['dna_original'] = $original;
    $_SESSION['dna_results'] = $results;
    $form_state['redirect'] = 'dna_success_page';
}

function dna_success() {
    $original = $_SESSION['dna_original'];
    $results = $_SESSION['dna_results'];
    return "
        <p>Sequence Entered: $original </p>
        <p>Matching Sequence: $results </p>
    ";
}

function matchDNA($sequence) {
    $letters = str_split($sequence);
    $matching_string = '';
    foreach($letters as $letter) {
        $match;
        switch($letter) {
            case 'C':
                $match = 'G';
                break;
            case 'G':
                $match = 'C';
                break;
            case 'T':
                $match = 'A';
                break;
            case 'A':
                $match = 'T';
                break;
        }
        $matching_string .= $match;
    }
    return $matching_string;
}
