<?php
function dna_menu() {
    $items = array();
    $items['dna_match'] = array(
            'title' => 'DNA Matcher',
            'access callback' => TRUE,
            'page callback' => 'drupal_get_form',
            'page arguments' => array('dna_form'),
            'type' => MENU_NORMAL_ITEM,
        );
    $items['dna_success_page'] = array(
            'title' => "DNA Matcher Success",
            'access callback' => TRUE,
            'page callback' => 'dna_success',
            'type' => MENU_CALLBACK,
        );
    return $items;
}

function dna_form() {
    $form = array();
    $form['sequence'] = array(
            '#title' => 'DNA Sequence',
            '#type' => 'textfield',
            '#description' => 'Enter one half of a DNA Helix and the other half will be returned',
        );
    $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Submit',
        );
    return $form;
}

function dna_form_submit($form, &$form_state) {
    $form_state['redirect'] = 'dna_success_page';
}

function dna_success() {
    return 'made it to success page';
}

function matchDNA($sequence) {
    $letters = str_split($sequence);
    $matching_string = '';
    foreach($letters as $letter) {
        $match;
        switch($letter) {
            case 'C':
                $match = 'G';
                break;
            case 'G':
                $match = 'C';
                break;
            case 'T':
                $match = 'A';
                break;
            case 'A':
                $match = 'T';
                break;
        }
        $matching_string .= $match;
    }
    return $matching_string;
}
